version: '3.8'

services:
  innovation-day-23-07-db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_ROOT_PASSWORD=123456
      - DATABASE_HOST=innovation-day-23-07-db
      - LOCAL_DATABASE_PORT=3306
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
